// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace WarOfHeroesUsersAPI.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210420140159_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarOfHeroesUsersAPI.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarOfHeroesUsersAPI.Data.Entities.UserHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserHero");
                });

            modelBuilder.Entity("WarOfHeroesUsersAPI.Data.Entities.UserHero", b =>
                {
                    b.HasOne("WarOfHeroesUsersAPI.Data.Entities.User", null)
                        .WithMany("Deck")
                        .HasForeignKey("UserId");

                    b.HasOne("WarOfHeroesUsersAPI.Data.Entities.User", null)
                        .WithMany("Inventory")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("WarOfHeroesUsersAPI.Data.Entities.User", b =>
                {
                    b.Navigation("Deck");

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
