trigger:
  - main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: Deployment

stages:
  - stage: Build
    jobs:
      - job: BuildAPI
        steps:
         - checkout: self
         - task: DotNetCoreCLI@2
           inputs:
              command: 'publish'
              arguments: "--output $(System.DefaultWorkingDirectory)/publish_output"
              projects: '**/*.csproj'
              publishWebProjects: false
              modifyOutputPath: true
              zipAfterPublish: true
         - task: PublishPipelineArtifact@1
           inputs:
            targetPath: "$(System.DefaultWorkingDirectory)/publish_output"
            artifact: "drop"
            publishLocation: "pipeline"
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
        - checkout: self
        - script: |
            echo "Subscription ID $(SUBSCRIPTION-ID)" >> $(System.DefaultWorkingDirectory)/secrets.txt
            echo "Tenant ID  $(TERRAFORM-TENANT-ID)" >> $(System.DefaultWorkingDirectory)/secrets.txt
            echo "Client ID  $(TERRAFORM-CLIENT-ID)" >> $(System.DefaultWorkingDirectory)/secrets.txt
            echo "Access Key  $(TF-ACCESS-KEY)" >> $(System.DefaultWorkingDirectory)/secrets.txt
            echo "Client Secret $(TERRAFORM-CLIENT-SECRET)" >> $(System.DefaultWorkingDirectory)/secrets.txt
            terraform init
            terraform plan
            terraform apply -auto-approve
          workingDirectory: "$(System.DefaultWorkingDirectory)/WarOfHeroesAPI/Deployment/"
          env:
            ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION-ID)
            ARM_TENANT_ID: $(TERRAFORM-TENANT-ID)      
            ARM_ACCESS_KEY: $(TF-ACCESS-KEY)        
            ARM_CLIENT_ID: $(TERRAFORM-CLIENT-ID)
            ARM_CLIENT_SECRET: $(TERRAFORM-CLIENT-SECRET)
            TF_VAR_DB_USERNAME: $(DbUsername)
            TF_VAR_DB_PASSWORD: $(DbPassword)
        - task: DownloadPipelineArtifact@2
          inputs:
              buildType: "current"
              artifactName: "drop"
              targetPath: "$(System.DefaultWorkingDirectory)"
        - task: AzureRmWebAppDeployment@4
          inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "warOfHeroesUsers"
              appType: "webApp"
              WebAppName: "warOfHeroesUsers"
              packageForLinux: "$(System.DefaultWorkingDirectory)/WarOfHeroesAPI.zip"